package id;

public enum BlockID 
{
	/*row 1*/
	SmoothStone(),
	CobbleStone(),
	Dirt(),
	Grass(),
	Sand(),
	RoughSteel(),
	Steel(),
	Brick(),
	/*row 2*/
	LightStone(),
	Gravel(),
	Iron(),
	GoldBrick(),
	BlueBlock(),
	CheckeredGreenBlock(),
	DiamondRedBlock(),
	SpiderWeb(),
	/*row 3*/
	MossyStone(),
	BookShelf(),
	GrayFlower(),
	BluePanel(),
	BlackPanel(),
	Snow(),
	Ice(),
	SnowDirt(),
	/*row 4*/
	RedLeafDirt(),
	RedLeaf(),
	Ladder(),
	PinkStone(),
	BrownStone(),
	Lava(),
	Water(),
	Mulch(),
	/*row 5*/
	Wood(),
	DarkLog(),
	BrightLeaf(),
	DarkLeaf(),
	Clock(),
	GreenStone(),
	CheckeredGreenStone(),
	GreenPanel(),
	/*row 6*/
	OrangeBlock(),
	PatternOrangeBlock(),
	CrackedOrangeBlock(),
	SmoothOrangeBlock(),
	PatternQuarts(),
	StarQuarts(),
	SmoothQuarts(),
	NoteBlock(),
	/*row 7*/
	PinkRock(),
	BorderPinkRock(),
	BlackPlate(),
	BrightLog(),
	PurpleWindow(),
	LightBlueWindow(),
	PinkWindow(),
	NeonBlue(),
	NeonMaroon(),
	NeonLightBlue(),
	NeonBlack(),
	NeonYellow(),
	NeonGreen(),
	NeonOrange(),
	NeonRed(),
	NeonWhite();
}